[package]
name = "core_ipp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
ipp = { workspace = true }
bytes = "1.5"
uuid = { workspace = true }
core_db = { path = "../core_db" }
core_identity = { path = "../core_identity" }
core_accounting = { path = "../core_accounting" }
core_dispatcher = { path = "../core_dispatcher" }
